### ISSUE TITLE
Znuny 7 - Client interface is unusable in mobile mode in Chrome on Android

### ISSUE THREAD

**Issue by cristalink** [znuny/Znuny#360]
### Environment

- OS:           Android 13, One UI 5.1, Samsung Galaxy S20
- Browser:      Chrome 111.0.5563.116
- Znuny version: 7.0.2

### Expected behaviour

The customer UI is supposed to be highly usable.

### Actual behaviour

Problem 1: There is simply not enough room to see the inbound message. Only a couple of lines ("Hi N...") fit and are shown. The inbound message can be scrolled, but I can still see only a couple of lines at a time. See Screenshot 1. 

Problem 2: If I tap the grey dot to the right of "Hi N..." (which is easy to do accidentally due to Problem 1), the HTML blocks get weirdly duplicated, and the inbound message gets copied to the first reply box. If I tap the grey dot again, things get duplicated again. See Screenshot 2.

The desktop mode seems to be OK at the first glance.

The Agent mobile interface has obvious problems, too, but it's not as critical. 

### How to reproduce

Log in to the customer interface and navigate to an open ticket in mobile mode.

### Screenshots

**NOTE: The screenshots are redacted with green boxes for privacy.**

Screenshot 1
![Screenshot_20230402_173843_Chrome](https://user-images.githubusercontent.com/27765666/229340781-fd82beb1-3fbb-4616-93ce-5997fd6058f4.jpg)

Screenshot 2
![Screenshot_20230402_174008_Chrome](https://user-images.githubusercontent.com/27765666/229340790-678def62-27d8-429c-a7bd-e1641ad443df.jpg)

Thanks!

**Comment by cristalink** [comment]
The issue can be reproduced in Chrome 111.0.5563.111 on Windows 11, Just resize the browser window to the smallest width. 

![image](https://user-images.githubusercontent.com/27765666/229342822-e65f1c26-042a-4342-ba12-5fd43fb9f0bc.png)

**Comment by hanneshal** [comment]
Hi @cristalink 
thanks for your issue and for the invested time. I put it on the internal list for fixes to come. 

Just to manage expectations a bit, our priorities are:
1) Desktop GUI - Issues
2) Addon Issues and ports to 7
3) Tablet GUI - Issues
4) Mobile (Phone) GUI - Issues

From the feedback we gathered within the last year, phone support was the least requested. 
But we will get onto this, as soon as the rest is somewhat sorted. 
Maybe we can slip this in the way somewhere. 
There will be more issues (sadly), because we decided during 
development and testing that we focus on tablet support and do not test on phone at all. 

Thanks again for the support. 
I get back to you when we fixed this.

Johannes

**Comment by cristalink** [comment]
It seems the issue still persists. I'd think the majority of customers use phones not tablets. An unusable ticket UI wouldn't make a good impression about the company.

**Comment by calebemelo** [comment]
The problem is also observed in version 7.2.3; with more and more users using mobile devices, a functional client interface would be very helpful.
